### ISSUE TITLE
incorrect arachnon spawning

### ISSUE THREAD

**Issue by redgoblin88** [andrew0030/Pandoras-Creatures#1]
hello, it seems that the arachnon mob spawns regardless of difficulty, and because of this they spawn EXTREMELY fast and despawn immedietly if you are in peaceful mode (like it sawns, the game checks if it can spawn, realises it shouldnt then despawns it)
In the attached file i have recorded a little clip of this bug

[New folder.zip](https://github.com/andrew0030/Pandoras-Creatures/files/3693255/New.folder.zip)

**Comment by andrew0030** [comment]
Ok I found the issue and I solved it, the problem will be gone in versions after 1.14.4-0.10.0
