### ISSUE TITLE
[BUG] Bug with VoxelMap

### ISSUE THREAD

**Issue by 36215764** [andrew0030/Pandoras-Creatures#10]
Hello, My Name is Richard, I am Brazilian

Help pelase!!!

 

I came through this to report a Bug in Pandoras Creatures with VoxelMap.

video is here:
[https://youtu.be/UNfVXxJNj4U](url)

While I'm next to the Arachnon Monster, the screen is giving a strange purple wink, only when I'm using VoxelMap, when I remove it from the Mods folder the bug stops.

 

I hope you fix it soon or help me fix this bug, why am I not leaving VoxelMap.

**Comment by frostfire50** [comment]
This is a known issue.

**Comment by frostfire50** [comment]
And will be fixed in the the next update.

**Comment by andrew0030** [comment]
> 
> 
> And will be fixed in the the next update.

Like I said on curse this is probably not even a problem on my end, so go ask the maker of VoxelMap.

**Comment by frostfire50** [comment]
Bruh I misread what you said on discord, you said you were gonna fix the world blender issue lol.

**Comment by 36215764** [comment]
> > And will be fixed in the the next update.
> 
> Like I said on curse this is probably not even a problem on my end, so go ask the maker of VoxelMap.

I'm already sending them too, there must be some texture error there, I thought it could be an error with the minimap icons, the icons of their Mobs, like when the radar icons go back to normal, and it's just with the your mod that has already added more monsters and remained normal on VoxelMap.
