### ISSUE TITLE
[BUG] Mod has unconfigured ConfiguredFeatures, according to the Blame Mod

### ISSUE THREAD

**Issue by V-Boy** [andrew0030/Pandoras-Creatures#17]
**Describe the bug**
The Blame Mod made reports that several features from this mod are not registered

**To Reproduce**
1. Startup MC with Blame and Pandora's
2. Create a world
3. Check your running log, the report should show up

**Expected behavior**
For the report not to show up

**Debug crash log**
https://hatebin.com/ozjfkbodht
**Versions**
1.16.3
Forge 34.1.11

**Comment by andrew0030** [comment]
Yeah, Im talking a lot with the developer of Blame, and he has also pointed this out to me. I will make sure to Register my ConfiguredFeatures properly for the next version.

**Comment by andrew0030** [comment]
Should be fixed in the next version after 1.16.3-2.0.0
