### ISSUE TITLE
[BUG] Sounds from mobs are weird, don't echo properly

### ISSUE THREAD

**Issue by V-Boy** [andrew0030/Pandoras-Creatures#19]
**Describe the bug**
The sounds from the mobs do not echo properly, and get cut off when you are a few blocks away

**To Reproduce**
1. Poison a mob
2. step a few blocks back
3. Notice how the mob sounds sound a bit off, they aren't dynamic and don't echo. They get cut off instantly 

**Expected behavior**
For them to echo like vanilla mobs

**Screenshots**
https://streamable.com/920l3i
Notice how when I fly a few blocks back, the Bufflon sounds instantly stop. The Bufflon sounds never lowered in volume either, stayed the same volume even though I was going back.

**Versions**
1.16.3
Forge 34.1.12

**Comment by andrew0030** [comment]
I fixed it, it will be available in versions after 1.16.3-2.0.0
