### ISSUE TITLE
[CRASH] Server Compability

### ISSUE THREAD

**Issue by djjosh05** [andrew0030/Pandoras-Creatures#2]
Hello, I am Josh, one of the people who tried putting your mod on a private forge "friends-only" modded server. I don't know if it's my side or your side, but your mod doesn't allow me to use it. Once I tried it and ran the forgerserver.jar, It had loaded the last mod, which was yours, and crashed, turning off rapidly on it's on. I go on trying to run the run.bat cmd, and it still doesn't work. It told me that an error had occured and that I needed to press any key to exit the .bat cmd, so I did.

Frankly, this might be me or the folder/system itself, as some other mods do this aswell. This is just a heads up to see if anything is wrong with it.

Love you, love your shoes, toodleoos,
Josh.

**Comment by andrew0030** [comment]
Can you give me the crash log or log? Something I can work with.
