### ISSUE TITLE
End Troll not obeying mobGriefing gamerule

### ISSUE THREAD

**Issue by Jakobuo** [andrew0030/Pandoras-Creatures#23]
The end troll still destroys blocks with mobGriefing set to false.

1.16.3

**Comment by andrew0030** [comment]
Yes I know, this isnt really a bug because otherwise the End Troll wouldn't be able to "escape" its prison. Its not a big deal really considering they only spawn in naturally generated structures in the End, far up in the sky.

**Comment by Jakobuo** [comment]
Yeah, but I'm trying to keep him contained for a dungeon I'm building.

**Comment by Jakobuo** [comment]
Any Idea how that could be eine?

**Comment by Jakobuo** [comment]
*done, not eine

**Comment by andrew0030** [comment]
Hm at the moment I dont think its possible as his scream attack will always break blocks. But if you want I could maybe add an option to the config that disables the block breaking. Or I make him check for the game rule after all.

**Comment by Jakobuo** [comment]
That would be really cool, thx.
Also, really cool mod.

**Comment by andrew0030** [comment]
also to be clear, I will do this for the latest version, I am not sure if I will also add this to older versions like 1.15 especially not 1.14 as I no longer support that version of the mod.

**Comment by Jakobuo** [comment]
Although the actual problem I have is that he keeps on jumping into the void when not being contained.
But thats probably a lot more work to fix?
Version is no problem, I'm on 1.16

**Comment by andrew0030** [comment]
Yeah I use vanilla path finding, so to fix it I would have to write my own and ensure its better, so the short answer is, yes, it would be **a lot** more work

**Comment by Jakobuo** [comment]
Ok config or whatever is just fine.
Thx again

**Comment by andrew0030** [comment]
Ok I just finished updating the End Troll, it was a rather easy thing to do. Any ways, versions after 1.16.3-2.0.1Will have End Trolls that check for the Mob Griefing game rule, in order to determine if they should break blocks or not!

**Comment by Jakobuo** [comment]
Thx a lot
