### ISSUE TITLE
[Bug] Treasure chests in vanilla structures are empty

### ISSUE THREAD

**Issue by Blugori** [andrew0030/Pandoras-Creatures#25]
Minecraft : 1.16.4
Forge : 35.1.0
Pandoras Creatures : 2.0.1

Hi ran into an issue, when I created a new world and joined, and then found a desert pyramid, all chests inside were empty. After several tests, I found that the issue appears only when pandoras creatures is installed (I use a lot of mods, so I don't really know if the issue can be fix on your side, but if you can help to find the problem that would be great !)

Ps : I use the "blame mod", wich adds a lot of lines in the logs, let me know if you want new logs without the infos from blame

[debug.log](https://github.com/andrew0030/Pandoras-Creatures/files/5578362/debug.log)
[latest.log](https://github.com/andrew0030/Pandoras-Creatures/files/5578363/latest.log)

Best regards !

**Comment by andrew0030** [comment]
I mean the easiest way to tell if the mod causes this, is to remove all mods except for PC and to try again.
Also keep in mind the latest version atm way made for 1.16.3, yes it can run on 1.16.4 but maybe it has issues

**Comment by Blugori** [comment]
When I try with only pandoras creatures, the loot generates, when I test my modpack, the loot generates, but when I add pandora's to the modpack, loot won't generate. I know that doesnt prove that the problem comes from pandora's, I was hoping you could have a hint on what's wrong haha 😅

**Comment by andrew0030** [comment]
Hm sounds like a mod compatibility issue

**Comment by andrew0030** [comment]
Do other loot chests generate ? Because I see a bunch of errors.
Let me know if its just the pyramids or if other loot chests like outposts wood land mansions and so on also do not contain any loot.

**Comment by Blugori** [comment]
So I've checked different vanilla structures and loot seems to generate in ruined portals, buried treasures and jungle temple, but not in desert pyramids and mansions.

**Comment by andrew0030** [comment]
Hm thats odd I do modify the loot table of the jungle pyramid, and I do not modify the mansions hmm I guess other mods that modify those loot tables seem to also have this issue

**Comment by Blugori** [comment]
I'm trying to isolate the mod that is causing conflict/bug with pandora's, but it's hard 😅

**Comment by Blugori** [comment]
I reduced the modpack to ~40 mods. I have different api/library. 
When I use those 40 mods with their respective libraries PLUS other useless libraries (used for other mods I put away for the moment), loot wont generate in desert pyramid.
When I use those 40 mods with their respective libraries WIHTOUT other useless libraries, loot generates in desert pyramid (I could find a bufflon saddle)
When I ONLY use the libraries (plus useless libraries, plus pandora's), loot generates in pyramids

**Comment by Blugori** [comment]
The mod causing issue is "Omni 1.1.0" !

Logs if you want to take a look, but since this error happened with different mods I'll open an issue on the omni github page !

[debug.log](https://github.com/andrew0030/Pandoras-Creatures/files/5585049/debug.log)
[latest.log](https://github.com/andrew0030/Pandoras-Creatures/files/5585050/latest.log)

**Comment by andrew0030** [comment]
Ah good to hear you managed to pinpoint it down :D

**Comment by Blugori** [comment]
Issue is fixed !
