### ISSUE TITLE
[FEATURE] Transforming ball

### ISSUE THREAD

**Issue by CursedWarrior10HD** [andrew0030/Pandoras-Creatures#5]
so there's another mob Idea I have which is to have a robot or ancient ball which can become in to tools that are better than diamond and attack players .They can be found in the End because there's aren't any mobs in the End dimension from the mod.
you can kill them and get the ball fragments to make your own transforming ball which can be used anywhere . When breaking a block with it,it turns it's model to the tool that is required to break it.

Hope you like this Idea and will add this mob in to your mod soon. 👍 
Hope you can make this mod successful

**Comment by andrew0030** [comment]
Suggestions will now be handled on discord
