### ISSUE TITLE
[BUG] Crash Ticking Entity while in The Nether.

### ISSUE THREAD

**Issue by Gbergz** [andrew0030/Pandoras-Creatures#7]
**Describe the bug**
In the Nether and an Entity is crashing one of my players playing my Pack. "Ticking Entity Crash"

**To Reproduce**
1. Go into the nether
2. Be there for awhile
3. Crash
4. See error [Hastebin](https://hastebin.com/onomepisik.rb)

**Expected behavior**
I expect to not crash while playing in the Nether.

**Debug crash log**
[Hastebin](https://hastebin.com/onomepisik.rb)

**Mod Version**
- 1.14.4-0.12.0

**Forge Version**
- 28.1.107

**MC Version** 
- 1.14.4

**Comment by andrew0030** [comment]
This seems to be the same issue that got reported here:
https://github.com/andrew0030/Pandoras-Creatures/issues/6

I changed some things and added a null check. So hopefully in version after 0.12.0 this bug will be gone

**Comment by Gbergz** [comment]
Any updates on when this update will be out to the public?

**Comment by andrew0030** [comment]
I dont have a planed release date, but if you want to stay updated my discord is probably the best place to be at

**Comment by andrew0030** [comment]
This bug was fixed in the latest update for 1.14.4 and the initial 1.15.2 version since I have gotten no further bug reports mentioning it, I will consider it solved.
