### ISSUE TITLE
[BUG] Permanent NoGravity Status Effect (archvine)

### ISSUE THREAD

**Issue by Darkfiend009** [andrew0030/Pandoras-Creatures#8]
A player using my modpack, Harrowing Adventure, was walking in the Nether and was sucked up to the ceiling. He was attacked by an Archvine, obviously. To escape, he used /home to teleport home. However, he is now permanently stuck with the NoGravity status regardless of the dimension he is in. The status effect won't clear.

Pandoras Creatures: 0.12.0
Minecraft: 1,14.4
Forge: 28.1.107

**Comment by andrew0030** [comment]
Ok so what happened there is your player pretty much interrupted the running AI of the archvine, you see usually the "effect" of no gravity goes away if the player dies or the plant dies. But if you just delete the plant or stop the AI through teleporting away like he did it can cause this issue. I will try to think of a solution but for now if you want it to stop, just let another archvine grab him. That should update his state.

**Comment by andrew0030** [comment]
This bug was fixed in the latest update for 1.14.4 and the initial 1.15.2 version since I have gotten no further bug reports mentioning it, I will consider it solved.
